spring.application.name=department_management
# =======================================
# DATABASE (PostgreSQL)
# =======================================
spring.datasource.url=jdbc:postgresql://localhost:5432/department_management
spring.datasource.username=postgres
spring.datasource.password=root
# =======================================
# JPA / HIBERNATE
# =======================================
spring.jpa.hibernate.ddl-auto=update
# =======================================
# SQL LOG
# =======================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
# =======================================
# FILE SAVE DIR
# =======================================
file.upload-dir=uploads
# =======================================
# FILE SIZE VALIDATE
# =======================================
# MAX SIZE OF 1 FILE
spring.servlet.multipart.max-file-size=2MB
# MAX SIZE OF REQUEST
spring.servlet.multipart.max-request-size=10MB
# Cloudinary Config (thong tin api ca nhan em khong push len github)
cloudinary.cloud-name=wazy4xz2
cloudinary.api-key=827569393619355
cloudinary.api-secret=UGvm21hSrLFrJo2mVlaXVxXZkr0